apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: access-control-xacml-2-0-context-schema-cd-04
  title: "access_control-xacml-2.0-context-schema-cd-04"
  description: "Shared interface: access_control-xacml-2.0-context-schema-cd-04.xsd (provided by balancemanagement-surepay-26-1-4)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04" xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04" elementFormDefault="qualified" attributeFormDefault="unqualified">
    	<xs:include schemaLocation="../../../../Infrastructure/V1/access_control-xacml-2.0-context-schema-cd-04.xsd"/>
    </xs:schema>
