apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: authenticateidentity-2-jsonresponse
  title: "AuthenticateIdentity.2-JSONResponse"
  description: "Shared interface: AuthenticateIdentity.2-JSONResponse.xsd (provided by customeridentitymanagement-idam-25-10-6)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    	 elementFormDefault="qualified"
    	 attributeFormDefault="unqualified">
    	<xs:element name="Error" type="JSONType"/>
    	<xs:complexType name="JSONType">
    		<xs:all>
    			<xs:element name="status" type="xs:string" minOccurs="0"/>
    			<xs:element name="code" type="xs:string" minOccurs="0"/>
    			<xs:element name="detailedCode" type="xs:string" minOccurs="0"/>
    			<xs:element name="detail" type="xs:string" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    <xs:element name="AuthenticateIdentityResponse" type="AuthenticateIdentityResponse"/>
    	<xs:complexType name="attributeType">
    		<xs:sequence>
    			<xs:element name="name" type="xs:string" minOccurs="0"/>
    			<xs:element name="type" type="xs:string" minOccurs="0"/>
    			<xs:element name="value" type="xs:string" minOccurs="0"/>
    			<xs:element name="id" type="xs:string" minOccurs="0"/>
    		</xs:sequence>
    	</xs:complexType>
    	<xs:complexType name="specificationType">
    		<xs:sequence>
    			<xs:element name="name" type="xs:string" minOccurs="0"/>
    			<xs:element name="type" type="xs:string" minOccurs="0"/>
    			<xs:element name="value" type="xs:string" minOccurs="0"/>
    			<xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
    		</xs:sequence>
    	</xs:complexType>
    	<xs:complexType name="AuthenticateIdentityResponse">
    		<xs:sequence>
    			<xs:element name="contactId" type="xs:string" minOccurs="0"/>
    			<xs:element name="onlineSessionToken" type="xs:string" minOccurs="0"/>
    			<xs:element name="specification" type="specificationType" minOccurs="0" maxOccurs="unbounded"/>
    		</xs:sequence>
    	</xs:complexType>
    </xs:schema>
