apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: bw5-apis
  title: "BW5 APIs"
spec:
  targets:
    - ./access-control-xacml-2-0-context-schema-cd-04.yaml
    - ./access-control-xacml-2-0-policy-schema-cd-04.yaml
    - ./addbillingbar.yaml
    - ./address-2.yaml
    - ./address.yaml
    - ./advanceshipmentnoticeebm.yaml
    - ./advanceshipmentnoticeebo.yaml
    - ./auditevent.yaml
    - ./authenticateidentity-2-jsonresponse.yaml
    - ./authenticateidentity-2-json.yaml
    - ./authenticateidentity-2.yaml
    - ./authenticateidentity-concrete-2.yaml
    - ./authenticateidentity.yaml
    - ./authenticateppinrequest.yaml
    - ./authenticateppinresponse.yaml
    - ./authnfpinpersistentrequest.yaml
    - ./authnfpinpersistentreq.yaml
    - ./authnfpinpersistentresponse.yaml
    - ./authnppinchallengeresponse.yaml
    - ./authnppintranchallengereq.yaml
    - ./authnppintranrequest.yaml
    - ./businesseventnotification-2.yaml
    - ./cancelreservedbalance-concrete.yaml
    - ./cancelreservedbalance.yaml
    - ./changebillingpattern.yaml
    - ./changecontactdetails.yaml
    - ./changepriceplan.yaml
    - ./channel.yaml
    - ./chargeaccountvalidate.yaml
    - ./codelists.yaml
    - ./commoncomponents.yaml
    - ./communication.yaml
    - ./connectivityservice.yaml
    - ./contact-2.yaml
    - ./createcase.yaml
    - ./createcustomerinteraction-client-concrete.yaml
    - ./createcustomerinteraction.yaml
    - ./createinteraction.yaml
    - ./creditbalance.yaml
    - ./creditcard.yaml
    - ./creditvetebo.yaml
    - ./crmcontactdetails.yaml
    - ./crmmarketingpreference.yaml
    - ./crmperson.yaml
    - ./curresponse.yaml
    - ./customadvanceshipmentnoticeebo.yaml
    - ./customcommoncomponents.yaml
    - ./customcustomerinteractionebo.yaml
    - ./customcustomerpartyebo.yaml
    - ./customerinteractionebm.yaml
    - ./customerinteractionebo.yaml
    - ./customernotifications-client-concrete-noreply.yaml
    - ./customernotifications-concrete.yaml
    - ./customernotifications.yaml
    - ./customerpartyebm.yaml
    - ./customerpartyebo.yaml
    - ./customersegment.yaml
    - ./customfulfillmentorderebo.yaml
    - ./custominstalledproductebo.yaml
    - ./custominventorytransactionebo.yaml
    - ./custommeta.yaml
    - ./customordereventebo.yaml
    - ./customprovisioningorderebo.yaml
    - ./customreceivedpaymentebo.yaml
    - ./customsalesorderebo.yaml
    - ./customserviceavailabilityebo.yaml
    - ./customserviceorderebo.yaml
    - ./customshipmentunit.yaml
    - ./datatypes.yaml
    - ./debitbalance.yaml
    - ./error.yaml
    - ./event.yaml
    - ./exceptionjmsmessage.yaml
    - ./exception.yaml
    - ./extendedjmsproperties.yaml
    - ./fault.yaml
    - ./findban.yaml
    - ./findbusinessban.yaml
    - ./findconsumerban.yaml
    - ./frameworkservices.yaml
    - ./fulfillmentorderebm.yaml
    - ./fulfillmentorderebo.yaml
    - ./getaccount.yaml
    - ./getbalance2common.yaml
    - ./getbalance2elements.yaml
    - ./getbalance-2-forcouk.yaml
    - ./getbalance-2.yaml
    - ./getbalance-3.yaml
    - ./getbalanceforban.yaml
    - ./getbalanceforbrm-client-concrete.yaml
    - ./getbalanceforbrm.yaml
    - ./getbalancepartialresponse.yaml
    - ./getbalanceresponse.yaml
    - ./getbalance.yaml
    - ./getbilldates.yaml
    - ./getbillformat.yaml
    - ./getbillinformation.yaml
    - ./getbillingarrangementdetails.yaml
    - ./getbilllist.yaml
    - ./getcontactdetails.yaml
    - ./getctnlistforbill.yaml
    - ./getcustomerdetails.yaml
    - ./getdatabalance.yaml
    - ./getdiscounts.yaml
    - ./gethlrsettings-2.yaml
    - ./gethlrsettings-client-concrete-2.yaml
    - ./getidentitylist-concrete.yaml
    - ./getidentitylistlegacy-json.yaml
    - ./getidentitylist.yaml
    - ./getinteractions.yaml
    - ./getitemisation.yaml
    - ./getnetworkaccessprofilelist.yaml
    - ./getoutofbundlechargesresponse.yaml
    - ./getoutofbundlecharges.yaml
    - ./getpaymentinformation-2.yaml
    - ./getpaymentinformation.yaml
    - ./getpinpositions-concrete.yaml
    - ./getpinpositionsrequest.yaml
    - ./getpinpositionsresponse.yaml
    - ./getpinpositions.yaml
    - ./getservicesummary-client-concrete.yaml
    - ./getservicesummary.yaml
    - ./getsubscriber-2.yaml
    - ./header.yaml
    - ./hss-shdata.yaml
    - ./identity.yaml
    - ./insertshipmentrequest.yaml
    - ./insertshipmentresponse.yaml
    - ./installedproductebm.yaml
    - ./installedproductebo.yaml
    - ./intnumber.yaml
    - ./inventorytransactionebm.yaml
    - ./inventorytransactionebo.yaml
    - ./invocationdetails.yaml
    - ./isgeminiavailable.yaml
    - ./jmsproperties.yaml
    - ./jsonerror.yaml
    - ./json.yaml
    - ./logon.yaml
    - ./meta.yaml
    - ./migrationrouter.yaml
    - ./msisdn.yaml
    - ./myoperation.yaml
    - ./notifybanandctn.yaml
    - ./notifyecareregistration.yaml
    - ./ordereventebo.yaml
    - ./osmtilinvocation.yaml
    - ./osmtilroutingconfig.yaml
    - ./osmtotilrouter.yaml
    - ./payment-api-v1-0.yaml
    - ./person-2.yaml
    - ./person.yaml
    - ./processapplication.yaml
    - ./provisioningorderebm.yaml
    - ./provisioningorderebo.yaml
    - ./querysimrtdb.yaml
    - ./receivedpaymentebm.yaml
    - ./receivedpaymentebo.yaml
    - ./registrationuserdetails-2.yaml
    - ./removebillingbar.yaml
    - ./requestheader.yaml
    - ./reservebalancecommon.yaml
    - ./reservebalanceelements.yaml
    - ./reservebalanceforcouk.yaml
    - ./reservebalance-json.yaml
    - ./reservebalancereq-json.yaml
    - ./reservebalanceres-json.yaml
    - ./reservebalance.yaml
    - ./reservectn.yaml
    - ./resource.yaml
    - ./responseheader.yaml
    - ./resultstatus-2.yaml
    - ./resultstatus.yaml
    - ./retrievehsslocationdetails-2.yaml
    - ./retrievehsslocationdetails.yaml
    - ./salesorderebm.yaml
    - ./salesorderebo.yaml
    - ./saml-schema-assertion-2-0.yaml
    - ./savecreditcheckresult.yaml
    - ./schema.yaml
    - ./sendadhoccardpayment.yaml
    - ./serviceavailabilityebo.yaml
    - ./serviceorderebm.yaml
    - ./serviceorderebo.yaml
    - ./setallocationcodes.yaml
    - ./setbillformat-2.yaml
    - ./setbillformat.yaml
    - ./setdiscount.yaml
    - ./setprintcategory.yaml
    - ./settlereservedbalance-concrete.yaml
    - ./settlereservedbalance-json.yaml
    - ./settlereservedbalance-request-json.yaml
    - ./settlereservedbalance-response-json.yaml
    - ./settlereservedbalance.yaml
    - ./shdatatype-rel15-nons.yaml
    - ./shdatatype-rel15.yaml
    - ./shdatatype-rel17-nons.yaml
    - ./shdatatype-rel17.yaml
    - ./shipmentunit.yaml
    - ./simpletypes-2.yaml
    - ./simpletypescrm.yaml
    - ./simpletypes.yaml
    - ./soap-envelope.yaml
    - ./subscribectn.yaml
    - ./svapsimpletypes.yaml
    - ./temp.yaml
    - ./tilfault.yaml
    - ./tiltoosmrouter.yaml
    - ./tokenintrospectrequest.yaml
    - ./tokenintrospectresponse.yaml
    - ./unreservectn.yaml
    - ./unsubscribewebservice.yaml
    - ./updatebillingarrangement.yaml
    - ./updatecontactdetails.yaml
    - ./updatecustomerdetails.yaml
    - ./updateidentity-concrete.yaml
    - ./updateidentityrequest.yaml
    - ./updateidentityresponse.yaml
    - ./updateidentity.yaml
    - ./updatemarketingpreferences.yaml
    - ./updatepassword-client-concrete.yaml
    - ./updatepassword-concrete.yaml
    - ./updatepassword.yaml
    - ./updateregistereduserdetails-2.yaml
    - ./userdataresponse.yaml
    - ./validateresource-client-concrete.yaml
    - ./validateresource.yaml
    - ./vfsubscriber.yaml
    - ./vfuserdetailsservice.yaml
    - ./writetolog.yaml
    - ./ws-addressing.yaml
    - ./wssecurity.yaml
    - ./wss-wssecurity-secext.yaml
    - ./wss-wssecurity-utility.yaml
    - ./xenc-schema.yaml
    - ./xmldsig-core-schema.yaml
    - ./xsdbuiltintypes.yaml
