apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: creditcard
  title: "CreditCard"
  description: "Shared interface: CreditCard.xsd (provided by customerbillproduction-gemini-24-5-2)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version = "1.0" encoding = "UTF-8"?>
    <?encrypt field="CreditCard/Details/regId" type="string"?>
    <?encrypt field="CreditCard/Details/status" type="string"?>
    <?encrypt field="CreditCard/pin" type="string"?>
    <?encrypt field="CreditCard/issueNumber" type="string"?>
    <!-- ICC: 25/07/2007 - TIL_XMLSCHEMAS_1_0_0 -->
    <?encrypt field="CreditCard/startDate" type="date"?>
    
    <?encrypt field="CreditCard/expiryDate" type="date"?>
    <?encrypt field="CreditCard/cardType" type="string"?>
    <?encrypt field="CreditCard/CVV2" type="string"?>
    <?encrypt field="CreditCard/cardNumber" type="string"?>
    
    <!--Generated by Turbo XML. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
    
    <!-- SCM: 26/03/2006 -->
    <!-- SCM: LLD v0.25 A Rivellini 22/11/2006 - changed to optional-->
    <!-- SCM: LLD v0.25 A Rivellini 22/11/2006 - changed to optional-->
    <!-- SCM: LLD v0.25 A Milner 22/11/2006 - changed datatype from string to dateTime-->
    
    <!-- ICC: 25/07/2007 - TIL_XMLSCHEMAS_1_0_0 -->
    <!-- ICC: Consolidation from TIL_SCM_IDC and TIL_MQSI -->
    <!-- ICC: Added startDate field -->
    
    <!-- TILV2: Header: /cvs/TIL_XML/SharedResources/SchemaDefinitions/Vodafone/Common/CommonObjects/CreditCard.xsd,v 1.2 2007/10/17 10:56:37 ayelr Exp  -->
    <!-- PXX: $Header: /cvs/TIL_XML/SharedResources/SchemaDefinitions/Vodafone/Common/CommonObjects/CreditCard.xsd,v 1.2 2007/10/17 10:56:37 ayelr Exp $ -->
    <schema xmlns = "http://www.w3.org/2001/XMLSchema"
    	 targetNamespace = "http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/CreditCard"
    	 xmlns:ccd = "http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/CreditCard"
    	 xmlns:address = "http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Address"
    	 xmlns:person = "http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Person"
    	 xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
    	 elementFormDefault = "qualified">
    	<import namespace = "http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Address" schemaLocation = "Address.xsd"/>
    	<import namespace = "http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Person" schemaLocation = "Person.xsd"/>
    
    	<complexType name = "CreditCard">
    		<sequence>
    			<element name = "cardNumber" type = "string" minOccurs = "0"/>
    			<element name = "CVV2" type = "string" minOccurs = "0"/>
    			<element name = "cardType" type = "string" minOccurs = "0"/>
    
    			<!-- ICC: 25/07/2007 - TIL_XMLSCHEMAS_1_0_0 -->
    			<element name = "startDate" type = "string" minOccurs = "0"/>
    
    			<element name = "expiryDate" type = "string" minOccurs = "0"/>
    			<element name = "issueNumber" type = "string" minOccurs = "0"/>
    			<element name = "pin" type = "string" minOccurs = "0"/>
    			<element name = "Owner" minOccurs = "0">
    				<complexType>
    					<sequence>
    						<element ref = "person:Person" minOccurs = "0"/>
    						<element ref = "address:Address" minOccurs = "0"/>
    					</sequence>
    				</complexType>
    			</element>
    			<element name = "Details" minOccurs = "0">
    				<complexType>
    					<sequence>
    						<element name = "status" type = "string" minOccurs = "0"/>
    						<element name = "regId" type = "string" minOccurs = "0"/>
    						<element name = "origCardNumber" type = "string" minOccurs = "0"/>
    						<element name = "origPin" type = "string" minOccurs = "0"/>
    						<element name = "updateRequired" type = "boolean" minOccurs = "0"/>
    					</sequence>
    				</complexType>
    			</element>
    			<element name = "registrationDateTime" type = "dateTime" minOccurs = "0"/>
    			<element name = "numberOfUpdates" type = "string" minOccurs = "0"/>
    		</sequence>
    	</complexType>
    	<element name = "CreditCard" type = "ccd:CreditCard"/>
    </schema>
