apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customserviceavailabilityebo
  title: "CustomServiceAvailabilityEBO"
  description: "Shared interface: CustomServiceAvailabilityEBO.xsd (provided by til-osm-adapter-1-22-2-1)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    
    <!--
    ** Version: 1.0 **
    ** Date: Apr 30, 2012 ** 
    -->
    <!-- ====================================================================== -->
    <!-- =====     Custom ServiceAvailability EBO Schema Module     ===== -->
    <!-- ====================================================================== -->
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    	 xmlns="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/ServiceAvailability/V2"
    	 xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
    	 xmlns:corecomcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
    	 targetNamespace="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/ServiceAvailability/V2"
    	 version="1.0.00"
    	 elementFormDefault="qualified"
    	 attributeFormDefault="unqualified">
    
    	<!-- ====================================================================== -->
    	<!-- ==============  Imports and Includes   =============================== -->
    	<!-- ====================================================================== -->
    	<xsd:import namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" schemaLocation="../../../../../../../../AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Industry/Communications/Common/V2/CommonComponents.xsd"/>
    	<xsd:import namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" schemaLocation="../../../../../../../../AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Industry/Communications/Common/V2/CodeLists.xsd"/>
    	<xsd:import namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" schemaLocation="../../../../../../../../AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Industry/Communications/Common/V2/DataTypes.xsd"/>
    	<xsd:import namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" schemaLocation="../../../../../../../../AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Industry/Communications/Common/V2/Meta.xsd"/>
    	<xsd:import namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2" schemaLocation="../../../../../../../../AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Industry/Communications/Custom/Common/V2/CustomCommonComponents.xsd"/>
    
    	<!-- ====================================================================== -->
    	<!-- ==============  ServiceAvailability Custom Components ================ -->
    	<!-- ====================================================================== -->
    	<xsd:complexType name="CustomServiceAvailabilityEBOType"/>
    	<xsd:complexType name="CustomExchangeDetailsType"/>
    </xsd:schema>
