apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: custommeta
  title: "CustomMeta"
  description: "Shared interface: CustomMeta.xsd (provided by balancemanagement-surepay-26-1-4)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
    ** Oracle Corporation  **
    ** AIA Enterprise Object Library **
    ** Version 1.00 **
    ** Date: 01 Nov 2007 **
    
     Copyright (c) 2007, 2010, Oracle and/or its affiliates. All rights reserved. 
    
    License information for this file is provided in the file 
    "Oracle AIA EBO License.txt" that is provided with this package.
      
        XML Schema 
        
        Name: \EnterpriseObjects\Release1\Core\Custom\Common\V2\CustomCommonComponents.xsd
    -->
    <!-- ====================================================================== -->
    <!-- =====      Oracle EBO Custom Comomn Components Schema Module     ===== -->
    <!-- ====================================================================== -->
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2" xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" targetNamespace="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.00">
    	<!-- ====================================================================== -->
    	<!-- =====      Imports                                                                                                      ===== -->
    	<!-- ====================================================================== -->
    	<xsd:import namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" schemaLocation="../../V1/DataTypes.xsd"/>
    	<xsd:import namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" schemaLocation="../../V1/CodeLists.xsd"/>
    	<xsd:complexType name="CustomEBMHeaderType">
    		<xsd:sequence>
    			<xsd:element name="ResponseNotification" type="CustomResponseNotificationType" minOccurs="0"/>
    			<xsd:element name="OriginatorSystemInfo" type="CustomOriginatorSystemInfoType" minOccurs="0"/>
    		</xsd:sequence>
    	</xsd:complexType>
    	<xsd:complexType name="CustomResponseNotificationType">
    		<xsd:sequence>
    			<xsd:element name="ElementPath" type="corecom:StringType" minOccurs="0"/>
    			<xsd:element name="Value" type="corecom:StringType" minOccurs="0"/>
    			<xsd:element name="StatusCode" type="corecom:CodeType" minOccurs="0"/>
    			<xsd:element name="Message" type="corecom:TextType" minOccurs="0"/>
    		</xsd:sequence>
    	</xsd:complexType>
    	<xsd:complexType name="CustomOriginatorSystemInfoType">
    		<xsd:sequence>
    			<xsd:element name="Type" type="corecom:CodeType" nillable="false" minOccurs="0"/>
    			<xsd:element name="User" type="corecom:NameType" nillable="false" minOccurs="0"/>
    			<xsd:element name="ParentBusinessID" type="corecom:StringType" nillable="false"/>
    			<xsd:element name="BusinessID" type="corecom:StringType" nillable="false"/>
    			<xsd:element name="DivisionName" type="corecom:StringType" nillable="false" minOccurs="0"/>
    			<xsd:element name="ContactID" type="corecom:StringType" nillable="false" minOccurs="0"/>
    			<xsd:element name="ExpiryDateTime" type="corecom:DateTimeType" nillable="false" minOccurs="0"/>
    			<xsd:element name="ListofParameters" minOccurs="0">
    				<xsd:complexType>
    					<xsd:sequence>
    						<xsd:element name="Parameter" maxOccurs="unbounded">
    							<xsd:complexType>
    								<xsd:sequence>
    									<xsd:element name="Name" type="corecom:StringType"/>
    									<xsd:element name="Value" type="corecom:StringType"/>
    								</xsd:sequence>
    							</xsd:complexType>
    						</xsd:element>
    					</xsd:sequence>
    				</xsd:complexType>
    			</xsd:element>
    		</xsd:sequence>
    	</xsd:complexType>
    	<xsd:complexType name="ParameterType">
    		<xsd:sequence>
    			<xsd:element name="Name" type="corecom:TextType" minOccurs="0"/>
    			<xsd:element name="Value" type="corecom:TextType" minOccurs="0"/>
    		</xsd:sequence>
    	</xsd:complexType>
    	<xsd:complexType name="ApplicationFaultDataType">
    		<xsd:sequence>
    			<xsd:element name="Code" type="corecom:CodeType" minOccurs="0"/>
    			<xsd:element name="Text" type="corecom:TextType" minOccurs="0"/>
    			<xsd:element name="System" type="corecom:TextType" minOccurs="0"/>
    			<!--
    			<xsd:element name="Severity" type="corecom:TextType" minOccurs="0"/>
    			<xsd:element name="Parameter" type="ParameterType" minOccurs="0"/>
    			<xsd:element name="Stack" type="xsd:anyType" minOccurs="0"/>
    			-->
    		</xsd:sequence>
    	</xsd:complexType>
    	<xsd:complexType name="CustomMessageProcessingInstructionType"/>
    	<xsd:complexType name="CustomSenderType"/>
    	<xsd:complexType name="CustomEBMTrackingType"/>
    	<xsd:complexType name="CustomTargetType"/>
    	<xsd:complexType name="CustomBusinessScopeType"/>
    	<xsd:complexType name="CustomIntermediateMessageHopType"/>
    	<xsd:complexType name="CustomB2BProfileType"/>
    	<xsd:complexType name="CustomSenderTradingPartnerType"/>
    	<xsd:complexType name="CustomReceiverTradingPartnerType"/>
    	<xsd:complexType name="CustomB2BMHeaderType"/>
    	<xsd:complexType name="CustomB2BDocumentTypeType"/>
    	<xsd:complexType name="CustomB2BMReferenceType"/>
    </xsd:schema>
