apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: getbalance
  title: "GetBalance"
  description: "Shared interface: GetBalance.xsd (provided by balancemanagement-surepay-26-1-4)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    	 elementFormDefault="qualified"
    	 attributeFormDefault="unqualified">
    	<xs:element name="GetBalance" type="JSONType"/>
    	<xs:complexType name="customerIdentificationType">
    		<xs:all>
    			<xs:element name="msisdn" type="xs:string" minOccurs="0"/>
    			<xs:element name="fln" type="xs:string" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="JSONType">
    		<xs:all>
    			<xs:element name="customerIdentification" type="customerIdentificationType" minOccurs="0"/>
    			<xs:element name="integrationID" type="xs:string" minOccurs="0"/>
    			<xs:element name="billingProfileID" type="xs:string" minOccurs="0"/>
    			<xs:element name="responseCode" type="xs:string" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    </xs:schema>
