apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: getbalanceresponse
  title: "GetBalanceResponse"
  description: "Shared interface: GetBalanceResponse.xsd (provided by balancemanagement-surepay-26-1-4)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    	 elementFormDefault="qualified"
    	 attributeFormDefault="unqualified">
    	<xs:element name="serviceBalance" type="serviceBalanceType"/>
    	<xs:complexType name="creditLimitRangeType">
    		<xs:all>
    			<xs:element name="maximumAllocated" type="xs:decimal" minOccurs="0"/>
    			<xs:element name="carriedOver" type="xs:decimal" minOccurs="0"/>
    			<xs:element name="maximumAvailable" type="xs:decimal" minOccurs="0"/>
    			<xs:element name="isUnlimited" type="xs:boolean" minOccurs="0"/>
    			<xs:element name="threshold" type="xs:decimal" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="periodTypeType">
    		<xs:all>
    			<xs:element name="from" type="xs:dateTime" minOccurs="0"/>
    			<xs:element name="to" type="xs:dateTime" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="serviceUnitType">
    		<xs:all>
    			<xs:element name="name" type="xs:string" minOccurs="0"/>
    			<xs:element name="description" type="xs:string" minOccurs="0"/>
    			<xs:element name="productID" type="xs:string" minOccurs="0"/>
    			<xs:element name="uom" type="xs:string" minOccurs="0"/>
    			<xs:element name="groupType" type="xs:string" minOccurs="0"/>
    			<xs:element name="balanceQuantity" type="balanceQuantityType" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="balanceQuantityType">
    		<xs:all>
    			<xs:element name="creditLimitRange" type="creditLimitRangeType" minOccurs="0"/>
    			<xs:element name="available" type="xs:decimal" minOccurs="0"/>
    			<xs:element name="usage" type="xs:decimal" minOccurs="0"/>
    			<xs:element name="periodType" type="periodTypeType" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="serviceBalanceType">
    		<xs:all>
    			<xs:element name="name" type="xs:string" minOccurs="0"/>
    			<xs:element name="description" type="xs:string" minOccurs="0"/>
    			<xs:element name="productID" type="xs:string" minOccurs="0"/>
    			<xs:element name="serviceUnit" type="serviceUnitType" maxOccurs="unbounded"/>
    		</xs:all>
    	</xs:complexType>
    </xs:schema>
