apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: identity
  title: "Identity"
  description: "Shared interface: Identity.xsd (provided by customeridentitymanagement-idam-25-10-6)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    
    <!-- edited with XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) by Altova XMLSpy 2017 Enterprise Edition (Hewlett Packard Enterprise Com) -->
    
    <!--	Updated by Anitha Govindasamy on 30/11/2020.
    	To include Audio block under VoicePrint.
    -->
    
    <schema xmlns="http://www.w3.org/2001/XMLSchema"
    	 xmlns:iden="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Identity/V2"
    	 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    	 xmlns:vod="http://xmlns.vodafone.co.uk/map/til/Common/SimpleTypes"
    	 xmlns:per="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Person"
    	 xmlns:comp="http://xmlns.vodafone.co.uk/map/til/Common/CommonComponents"
    	 targetNamespace="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Identity/V2"
    	 elementFormDefault="qualified"
    	 attributeFormDefault="unqualified">
    	<import namespace="http://xmlns.vodafone.co.uk/map/til/Common/SimpleTypes" schemaLocation="../SimpleTypes.2.xsd"/>
    	<import namespace="http://xmlns.vodafone.co.uk/map/til/Common/CommonComponents" schemaLocation="../CommonComponents.xsd"/>
    	<import namespace="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Person" schemaLocation="Person.2.xsd"/>
    	<complexType name="IdentityType">
    		<complexContent>
    			<extension base="per:PersonType">
    				<sequence>
    					<element name="Contact" type="comp:ContactType" minOccurs="0"/>
    					<element name="UserName" type="xsd:string" minOccurs="0"/>
    					<element name="Password" type="iden:PasswordType" minOccurs="0"/>
    					<element name="PIN" type="iden:PINType" minOccurs="0"/>
    					<element name="Status" type="xsd:string" minOccurs="0"/>
    					<element name="SecretList" type="iden:SecretListType" minOccurs="0"/>
    					<element name="MemorablePair" type="iden:MemorablePairType" minOccurs="0"/>
    					<element name="Biometric" type="iden:BiometricType" minOccurs="0"/>
    				</sequence>
    			</extension>
    		</complexContent>
    	</complexType>
    	<complexType name="PINType">
    		<sequence>
    			<element name="Type" type="xsd:string" minOccurs="0"/>
    			<element name="Value" type="xsd:string" minOccurs="0"/>
    			<element name="Positions" type="xsd:integer" minOccurs="0"/>
    			<element name="Status" type="xsd:string" minOccurs="0"/>
    			<element name="UpdatedDateTime" type="xsd:dateTime" minOccurs="0"/>
    			<element name="ValidityPeriod" type="comp:PeriodType" minOccurs="0"/>
    		</sequence>
    	</complexType>
    	<complexType name="PasswordType">
    		<sequence>
    			<element name="Value" type="xsd:string" minOccurs="0"/>
    			<element name="Status" type="xsd:string" minOccurs="0"/>
    			<element name="UpdatedDateTime" type="xsd:dateTime" minOccurs="0"/>
    			<element name="ValidityPeriod" type="comp:PeriodType" minOccurs="0"/>
    		</sequence>
    	</complexType>
    	<complexType name="SecretListType">
    		<sequence>
    			<element name="Secret" type="iden:SecretType" minOccurs="0" maxOccurs="unbounded"/>
    		</sequence>
    	</complexType>
    	<complexType name="SecretType">
    		<sequence>
    			<element name="Question" type="xsd:string" minOccurs="0"/>
    			<element name="Answer" type="xsd:string" minOccurs="0"/>
    		</sequence>
    	</complexType>
    	<complexType name="MemorablePairType">
    		<sequence>
    			<element name="MemorableWord" type="xsd:string" minOccurs="0"/>
    			<element name="Hint" type="xsd:string" minOccurs="0"/>
    		</sequence>
    	</complexType>
    	<complexType name="BiometricType">
    		<sequence>
    			<element name="VoicePrint" minOccurs="0">
    				<complexType>
    					<sequence>
    						<element name="LockStatus" type="xsd:string" minOccurs="0">
    							<annotation>
    								<documentation>If locked, a voiceprint cannot be used for voiceprint verification</documentation>
    							</annotation>
    						</element>
    						<element name="LockReason" type="xsd:string" minOccurs="0">
    							<annotation>
    								<documentation>Text reason recorded at the time that VoicePrint lock status was set to locked.</documentation>
    							</annotation>
    						</element>
    						<element name="LockTime" type="xsd:dateTime" minOccurs="0">
    							<annotation>
    								<documentation>Time that the voiceprint lock status was set to locked.</documentation>
    							</annotation>
    						</element>
    						<element name="TrainedStatus" type="xsd:boolean" minOccurs="0">
    							<annotation>
    								<documentation>If trained, the voiceprint can be used to verify a speaker's voiceprint</documentation>
    							</annotation>
    						</element>
    						<element name="Audio" minOccurs="0">
    							<complexType>
    								<sequence>
    									<element name="Mode" type="xsd:string" minOccurs="0">
    										<annotation>
    											<documentation>Mode through which audio is delivered to the system. </documentation>
    										</annotation>
    									</element>
    									<element name="Value" type="xsd:string" minOccurs="0">
    										<annotation>
    											<documentation>Value of the mode/format through which audio is being delivered</documentation>
    										</annotation>
    									</element>
    								</sequence>
    							</complexType>
    						</element>
    					</sequence>
    				</complexType>
    			</element>
    		</sequence>
    	</complexType>
    	<element name="Identity" type="iden:IdentityType"/>
    </schema>
