apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: insertshipmentrequest
  title: "InsertShipmentRequest"
  description: "Shared interface: InsertShipmentRequest.xsd (provided by customeridentitymanagement-idam-25-10-6)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    	 elementFormDefault="qualified"
    	 attributeFormDefault="unqualified">
    	<xs:element name="JSON" type="JSONType"/>
    	<xs:complexType name="parcelProductType">
    		<xs:all>
    			<xs:element name="countryOfOrigin" type="xs:string" minOccurs="0"/>
    			<xs:element name="numberOfItems" type="xs:integer" minOccurs="0"/>
    			<xs:element name="productCode" type="xs:string" minOccurs="0"/>
    			<xs:element name="productFabricContent" type="xs:string" minOccurs="0"/>
    			<xs:element name="productHarmonisedCode" type="xs:string" minOccurs="0"/>
    			<xs:element name="productItemsDescription" type="xs:string" minOccurs="0"/>
    			<xs:element name="productTypeDescription" type="xs:string" minOccurs="0"/>
    			<xs:element name="unitValue" type="xs:float" minOccurs="0"/>
    			<xs:element name="unitWeight" type="xs:float" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="parcelType">
    		<xs:all>
    			<xs:element name="isVoided" type="xs:boolean" minOccurs="0"/>
    			<xs:element name="labelNumber" type="xs:string" minOccurs="0"/>
    			<xs:element name="packageNumber" type="xs:integer" minOccurs="0"/>
    			<xs:element name="parcelNumber" type="xs:string" minOccurs="0"/>
    			<xs:element name="parcelProduct" type="parcelProductType" minOccurs="0"/>
    			<xs:element name="parcelnetBarcode" type="xs:string" minOccurs="0"/>
    			<xs:element name="parcelnetData" type="xs:string" minOccurs="0"/>
    			<xs:element name="parcelnetLabelNumber" type="xs:string" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="contactDetailsType">
    		<xs:all>
    			<xs:element name="contactName" type="xs:string" minOccurs="0"/>
    			<xs:element name="telephone" type="xs:string" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="addressType">
    		<xs:all>
    			<xs:element name="organisation" type="xs:string" minOccurs="0"/>
    			<xs:element name="countryCode" type="xs:string" minOccurs="0"/>
    			<xs:element name="postcode" type="xs:string" minOccurs="0"/>
    			<xs:element name="street" type="xs:string" minOccurs="0"/>
    			<xs:element name="locality" type="xs:string" minOccurs="0"/>
    			<xs:element name="town" type="xs:string" minOccurs="0"/>
    			<xs:element name="county" type="xs:string" minOccurs="0"/>
    			<xs:element name="countryName" type="xs:string" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="invoiceItemType">
    		<xs:all>
    			<xs:element name="countryOfOrigin" type="xs:string" minOccurs="0"/>
    			<xs:element name="itemCode" type="xs:string" minOccurs="0"/>
    			<xs:element name="itemDescription" type="xs:string" minOccurs="0"/>
    			<xs:element name="numberOfItems" type="xs:integer" minOccurs="0"/>
    			<xs:element name="unitValue" type="xs:float" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="invoiceBillingDetailsType">
    		<xs:all>
    			<xs:element name="address" type="addressType" minOccurs="0"/>
    			<xs:element name="contactDetails" type="contactDetailsType" minOccurs="0"/>
    			<xs:element name="vatNumber" type="xs:string" minOccurs="0"/>
    		</xs:all>
    	</xs:complexType>
    	<xs:complexType name="invoiceType">
    		<xs:sequence>
    			<xs:element name="countryOfOrigin" type="addressType" minOccurs="0"/>
    			<xs:element name="invoiceBillingDetails" type="invoiceBillingDetailsType" minOccurs="0"/>
    			<xs:element name="invoiceCustomsNumber" type="xs:string" minOccurs="0"/>
    			<xs:element name="invoiceExportReason" type="xs:string" minOccurs="0"/>
    			<xs:element name="invoiceIsDeclared" type="xs:boolean" minOccurs="0"/>
    			<xs:element name="invoiceItem" type="invoiceItemType" minOccurs="0" maxOccurs="unbounded"/>
    			<xs:element name="invoiceTermsOfDelivery" type="xs:string" minOccurs="0"/>
    			<xs:element name="invoiceType" type="xs:integer" minOccurs="0"/>
    			<xs:element name="totalItems" type="xs:integer" minOccurs="0"/>
    			<xs:element name="totalValue" type="xs:float" minOccurs="0"/>
    			<xs:element name="totalWeight" type="xs:float" minOccurs="0"/>
    		</xs:sequence>
    	</xs:complexType>
    	<xs:complexType name="JSONType">
    		<xs:sequence>
    			<xs:element name="job_id" type="xs:integer" minOccurs="0"/>
    			<xs:element name="collectionOnDelivery" type="xs:boolean" minOccurs="0"/>
    			<xs:element name="invoice" type="invoiceType" minOccurs="0"/>
    			<xs:element name="collectionDate" type="xs:dateTime" minOccurs="0"/>
    			<xs:element name="consolidate" type="xs:boolean" minOccurs="0"/>
    			<xs:element name="consignment" minOccurs="0" maxOccurs="unbounded">
    				<xs:complexType>
    					<xs:sequence>
    						<xs:element name="consignmentNumber" type="xs:string" minOccurs="0"/>
    						<xs:element name="consignmentRef" type="xs:string" minOccurs="0"/>
    						<xs:element name="parcels" type="parcelType" minOccurs="0" maxOccurs="unbounded"/>
    						<xs:element name="collectionDetails" minOccurs="0">
    							<xs:complexType>
    								<xs:all>
    									<xs:element name="contactDetails" type="contactDetailsType" minOccurs="0"/>
    									<xs:element name="address" type="addressType" minOccurs="0"/>
    								</xs:all>
    							</xs:complexType>
    						</xs:element>
    						<xs:element name="deliveryDetails" minOccurs="0">
    							<xs:complexType>
    								<xs:all>
    									<xs:element name="contactDetails" type="contactDetailsType" minOccurs="0"/>
    									<xs:element name="address" type="addressType" minOccurs="0"/>
    									<xs:element name="notificationDetails" minOccurs="0">
    										<xs:complexType>
    											<xs:all>
    												<xs:element name="email" type="xs:string" minOccurs="0"/>
    												<xs:element name="mobile" type="xs:string" minOccurs="0"/>
    											</xs:all>
    										</xs:complexType>
    									</xs:element>
    								</xs:all>
    							</xs:complexType>
    						</xs:element>
    						<xs:element name="networkCode" type="xs:string" minOccurs="0"/>
    						<xs:element name="numberOfParcels" type="xs:integer" minOccurs="0"/>
    						<xs:element name="totalWeight" type="xs:float" minOccurs="0"/>
    						<xs:element name="shippingRef1" type="xs:string" minOccurs="0"/>
    						<xs:element name="shippingRef2" type="xs:string" minOccurs="0"/>
    						<xs:element name="shippingRef3" type="xs:string" minOccurs="0"/>
    						<xs:element name="customsValue" type="xs:float" minOccurs="0"/>
    						<xs:element name="deliveryInstructions" type="xs:string" minOccurs="0"/>
    						<xs:element name="parcelDescription" type="xs:string" minOccurs="0"/>
    						<xs:element name="liabilityValue" type="xs:float" minOccurs="0"/>
    						<xs:element name="liability" type="xs:boolean" minOccurs="0"/>
    					</xs:sequence>
    				</xs:complexType>
    			</xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:schema>
