apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: reservebalanceelements
  title: "ReserveBalanceElements"
  description: "Shared interface: ReserveBalanceElements.xsd (provided by balancemanagement-surepay-26-1-4)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns="http://xmlns.vodafone.co.uk/map/til/Billing/BalanceManagement/DebitCreditManagement/ReserveBalanceElements" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:ns2="http://xmlns.vodafone.co.uk/map/til/Billing/BalanceManagement/DebitCreditManagement/ReserveBalanceCommon" 
    targetNamespace="http://xmlns.vodafone.co.uk/map/til/Billing/BalanceManagement/DebitCreditManagement/ReserveBalanceElements">
    	<xs:import namespace="http://xmlns.vodafone.co.uk/map/til/Billing/BalanceManagement/DebitCreditManagement/ReserveBalanceCommon" schemaLocation="ReserveBalanceCommon.xsd"/>
    	
    	
    		<xs:complexType name="ReceivedPaymentEBMType">
    			<xs:sequence>
    				<xs:element ref="ns2:Identification" minOccurs="0"/>
    				<xs:element name="PaymentMethodCode" type="xs:string" minOccurs="0"/>
    				<xs:element name="AuthorizationAmount" type="xs:decimal" minOccurs="0"/>
    				<xs:element name="ConfirmationNumber" type="xs:string" minOccurs="0"/>
    			</xs:sequence>
    		</xs:complexType>
    
    </xs:schema>
