apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tilfault
  title: "TILFault"
  description: "Shared interface: TILFault.wsdl (provided by til-osm-adapter-1-22-2-1)"
  tags:
    - tibco
    - bw5
spec:
  type: openapi
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- ICC: 23/05/2012 - LIB_FRAMEWORK_4_0_0 -->
    <!-- ICC: First version -->
    <!-- TILV2: Header: /cvs/TIL_V2/SharedResources/SchemaDefinitions/Vodafone/GITA1/GITA2/GITA3/MyOperation.wsdl,v 1.7 2008/08/01 11:45:28 ayelr Exp  -->
    <!-- PXX: $Header: /cvs/TIL_CORE/TIL_FW_01/SharedResources/SchemaDefinitions/Common/wsdl/TILFault.wsdl,v 1.2 2012/05/29 15:08:09 ayelr Exp $ -->
    <definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://xmlns.vodafone.co.uk/map/til/Common/ResultStatus" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.tibco.com/common/wsdl/TILFault" targetNamespace="http://xmlns.tibco.com/common/wsdl/TILFault" name="TILFault">
        <import namespace="http://xmlns.vodafone.co.uk/map/til/Common/ResultStatus" location="../../Vodafone/Common/ResultStatus.xsd"/>
        <message name="TILFault">
            <part name="part1" element="ns:ResultStatus"/>
        </message>
    </definitions>
