apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: updateregistereduserdetails-2
  title: "UpdateRegisteredUserDetails.2"
  description: "Shared interface: UpdateRegisteredUserDetails.2.xsd (provided by customeridentitymanagement-idam-25-10-6)"
  tags:
    - tibco
    - bw5
spec:
  type: grpc
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    
    <!-- $Header: /cvs/TSTIL_PROJECT01/SharedResources/SchemaDefinitions/Vodafone/CustomerManagement/CustomerProfileManagement/CustomerPersonalInformationManagement/UpdateRegisteredUserDetails.2.xsd,v 1.9 2015/04/25 08:16:59 tparames Exp $ -->
    <!-- Usage for secret question and secret answer : -->
    <!-- The Secret question & answer attributes are used from RegistrationUserDetails.xsd of common objects and should not be passed as part of credential type. -->
    <!-- Version 1.0
    
       ICC:Kumaravel Naryanan:
                Added UserStatus, ServiceStatus & CredentialsStatus in UpdateRegisteredUserDetailsResponse
    
       ICC: Pierre Ayel 03/11/2009 - Project Total Comms SA Drop 3
          (1) Added "hasMailboxId" in the reply 
          (2) Added "UID" in the reply 
          
       ICC: Pierre Ayel 11/11/2009 - Project Total Comms SA Drop3
          (1) Changed type of new reply element "UID" into UUID
          (2) Changed type of request element "MSISDN" into PHONENUMBER
    
       ICC: Pierre Ayel 16/02/2010 - Project Total Comms SA Drop3
          (1) Added new method "AddAnonymous"
    
       ICC: Pierre Ayel 15/04/2010 - Project Total Comms SA Drop3
          (1) Defect 4527: Added optional boolean input element "returnUID" 
    	  
    	Priy Ranjan 22/02/2012 - Project NewCo 
    	   CR:71 : Added input string element "adultBar" and "adultBarEntitlement" in UpdateRegisteredUserDetailsRequest
    	
       ICC: Sandeep Bhardwaj 23/04/2015 - Project P11
    		Changed type of request element "MSISDN" to string to remove validation to support TV & Broadband IDs   
    -->
    <schema xmlns="http://www.w3.org/2001/XMLSchema"
    	 xmlns:til="http://xmlns.vodafone.co.uk/map/til/CustomerManagement/CustomerProfileManagement/CustomerPersonalInformationManagement/UpdateRegisteredUserDetails"
    	 xmlns:vod="http://xmlns.vodafone.co.uk/map/til/Common/SimpleTypes"
    	 xmlns:rs="http://xmlns.vodafone.co.uk/map/til/Common/ResultStatus"
    	 xmlns:ad="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Address"
    	 xmlns:per="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Person"
    	 xmlns:usr="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/RegistrationUserDetails"
    	 xmlns:log="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Logon"
    	 targetNamespace="http://xmlns.vodafone.co.uk/map/til/CustomerManagement/CustomerProfileManagement/CustomerPersonalInformationManagement/UpdateRegisteredUserDetails"
    	 elementFormDefault="qualified"
    	 attributeFormDefault="unqualified">
    	<import namespace="http://xmlns.vodafone.co.uk/map/til/Common/SimpleTypes" schemaLocation="../../../Common/SimpleTypes.xsd"/>
    	<import namespace="http://xmlns.vodafone.co.uk/map/til/Common/ResultStatus" schemaLocation="../../../Common/ResultStatus.xsd"/>
    	<import namespace="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Address" schemaLocation="../../../Common/CommonObjects/Address.xsd"/>
    	<import namespace="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Person" schemaLocation="../../../Common/CommonObjects/Person.xsd"/>
    	<import namespace="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/RegistrationUserDetails" schemaLocation="../../../Common/CommonObjects/RegistrationUserDetails.2.xsd"/>
    	<import namespace="http://xmlns.vodafone.co.uk/map/til/Common/CommonObjects/Logon" schemaLocation="../../../Common/CommonObjects/Logon.xsd"/>
    	<simpleType name="MethodType">
    		<restriction base="string">
    			<enumeration value="Add"/>
    
    			<!-- Total Comms Service Activation DROP3 -->
    			<enumeration value="AddAnonymous"/>
    			<enumeration value="Modify"/>
    			<enumeration value="Delete"/>
    			<enumeration value="UpdateUsername"/>
    		</restriction>
    	</simpleType>
    	<complexType name="UserType">
    		<sequence>
    			<element name="method" type="til:MethodType"/>
    			<element name="changedUserName" type="string" minOccurs="0"/>
    			<element ref="per:Person" minOccurs="0"/>
    			<element ref="ad:Address" minOccurs="0"/>
    			<element ref="usr:RegistrationUserDetails" minOccurs="0"/>
    		</sequence>
    	</complexType>
    	<element name="UserType" type="til:UserType"/>
    	<complexType name="Credential">
    		<sequence>
    			<element name="credentialType" type="string"/>
    			<element name="oldValue" type="string" minOccurs="0"/>
    			<element name="newValue" type="string" minOccurs="0"/>
    			<element name="isTemporary" type="boolean" minOccurs="0"/>
    			<element name="isLock" type="boolean" minOccurs="0"/>
    		</sequence>
    	</complexType>
    	<element name="Credential" type="til:Credential"/>
    	<complexType name="CredentialType">
    		<sequence>
    			<element name="method" type="til:MethodType"/>
    			<element name="Credential" type="til:Credential" minOccurs="0" maxOccurs="unbounded"/>
    		</sequence>
    	</complexType>
    	<element name="CredentialType" type="til:CredentialType"/>
    	<complexType name="StatusType">
    		<sequence>
    			<element name="isSuccess" type="boolean"/>
    			<element name="Failure" minOccurs="0" maxOccurs="unbounded">
    				<complexType>
    					<sequence>
    						<element name="code" type="string"/>
    						<element name="message" type="string"/>
    						<element name="method" type="string"/>
    					</sequence>
    				</complexType>
    			</element>
    		</sequence>
    	</complexType>
    	<element name="StatusType" type="til:StatusType"/>
    	<complexType name="UpdateRegisteredUserDetailsRequest">
    		<sequence>
    			<choice>
    				<element name="MSISDN" type="string"/>
    				<element name="userName" type="string"/>
    				<element name="ASID" type="vod:UUID"/>
    				<element name="CSR" type="vod:UUID"/>
    				<element name="UID" type="vod:UUID"/>
    			</choice>
    			<element name="User" type="til:UserType" minOccurs="0"/>
    			<element name="Credentials" type="til:CredentialType" minOccurs="0"/>
    			<element name="Logon" type="log:Logon" minOccurs="0"/>
    			<element name="adultBar" type="string" minOccurs="0"/>
    			<element name="adultBarEntitlement" type="string" minOccurs="0"/>
    			<element name="returnUID" type="boolean" minOccurs="0"/>
    		</sequence>
    	</complexType>
    	<element name="UpdateRegisteredUserDetailsRequest" type="til:UpdateRegisteredUserDetailsRequest"/>
    	<complexType name="UpdateRegisteredUserDetailsResponse">
    		<sequence>
    			<element ref="rs:ResultStatus"/>
    			<element name="UserStatus" type="til:StatusType" minOccurs="0"/>
    			<element name="CredentialsStatus" type="til:StatusType" minOccurs="0"/>
    
    			<!-- Total Comms SA Drop 3 -->
    			<element name="UID" type="vod:UUID" minOccurs="0"/>
    		</sequence>
    	</complexType>
    	<element name="UpdateRegisteredUserDetailsResponse" type="til:UpdateRegisteredUserDetailsResponse"/>
    </schema>
