apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: http-listen-greeting
  title: "greeting listener /"
  description: "greeting listener / — inbound (/)"
  tags:
    - tibco
    - bw5
    - http
    - rest
spec:
  type: http-endpoint
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
