apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jms-dest-env-jms-mig-jms-dest-prefix-if-processes-itintegration
  title: "%%Env/JMS/MIG_Jms_Dest_Prefix_IF%%.%%Processes/ITIntegration/ApplicationIntegration/Routing/TILtoOSMRouter/Operation6/MIG_TILRouterQueue%%"
  description: "%%Env/JMS/MIG_Jms_Dest_Prefix_IF%%.%%Processes/ITIntegration/ApplicationIntegration/Routing/TILtoOSMRouter/Operation6/MIG_TILRouterQueue%%"
  tags:
    - tibco
    - bw5
    - messaging
    - jms
    - destination
spec:
  type: jms-destination
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
