apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jms-dest-ftlqueueout
  title: "ftlqueueout"
  description: "ftlqueueout"
  tags:
    - tibco
    - bw5
    - messaging
    - jms
    - destination
spec:
  type: jms-destination
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
