apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jms-dest-env-jms-mig-jms-dest-prefix-internal-env-jms-errorhand
  title: "%%Env/JMS/MIG_Jms_Dest_Prefix_Internal%%.%%Env/JMS/ErrorHandling/GLB_JMS_ExceptionNotifyTopic%%"
  description: "%%Env/JMS/MIG_Jms_Dest_Prefix_Internal%%.%%Env/JMS/ErrorHandling/GLB_JMS_ExceptionNotifyTopic%%"
  tags:
    - tibco
    - bw5
    - messaging
    - jms
    - destination
spec:
  type: jms-destination
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
