apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jms-dest-ftlqueuein
  title: "ftlqueuein"
  description: "ftlqueuein"
  tags:
    - tibco
    - bw5
    - messaging
    - jms
    - destination
spec:
  type: jms-destination
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
