apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jms-dest-env-jms-mig-jms-dest-prefix-if-notify-soap-cust-ordcap
  title: "%%Env/JMS/MIG_Jms_Dest_Prefix_IF%%.Notify.SOAP.CUST.OrdCapVal.CommercialOrderValidation.BusinessEventNotification.FixedLineOrderNotification.OSM.2.Router"
  description: "%%Env/JMS/MIG_Jms_Dest_Prefix_IF%%.Notify.SOAP.CUST.OrdCapVal.CommercialOrderValidation.BusinessEventNotification.FixedLineOrderNotification.OSM.2.Router"
  tags:
    - tibco
    - bw5
    - messaging
    - jms
    - destination
spec:
  type: jms-destination
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
